version: '3.7'

services:
  mongodb:
    image: mongo:4.4.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "budget-user"
      MONGO_INITDB_ROOT_PASSWORD: "budget-password"
      MONGO_INITDB_DATABASE: "budget-tracker"
    ports:
        - 27017:27017
    volumes:
        - ./data/mongodb:/data/db
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro