consumes:
- application/json
definitions:
  JWTUser:
    description: JWTUser defines a user to generate JWT tokens
    properties:
      login:
        description: ID primitive.ObjectID `json:"id,omitempty" bson:"_id,omitempty"`
        example: vsantos
        type: string
        x-go-name: Login
      password:
        example: myplaintextpassword
        type: string
        x-go-name: Password
    type: object
    x-go-package: budget-tracker/models
  User:
    description: User struct defines a user
    properties:
      email:
        example: vsantos.py@gmail.com
        type: string
        x-go-name: Email
      firstname:
        example: Victor
        type: string
        x-go-name: Firstname
      lastname:
        example: Santos
        type: string
        x-go-name: Lastname
      login:
        example: vsantos
        type: string
        x-go-name: Login
      password:
        example: myplaintextpassword
        type: string
        x-go-name: SaltedPassword
    type: object
    x-go-package: budget-tracker/models
host: budget-tracker:8080
info:
  contact:
    email: vsantos.py@gmail.com
    name: Victor Santos
    url: https://github.com/vsantos
  description: |-
    the purpose of this application is to provide an application
    that is using plain go code to define an API

    This should demonstrate all the possible comment annotations
    that are available to turn go code into a fully compliant swagger 2.0 spec
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  termsOfService: there are no TOS at this moment, use at your own risk we take no responsibility
  title: Budget-tracker API.
  version: 0.0.1
paths:
  /api/v1/jwt/issue:
    post:
      consumes:
      - application/json
      description: Returns a JWT signed token to be used for the next 5 minutes
      operationId: issue
      parameters:
      - description: application/json
        in: headers
        name: content-type
        required: true
      - description: credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/JWTUser'
      produces:
      - application/json
      responses:
        "201":
          description: returned JWT token
          examples:
            application/json:
              refresh: <REFRESH_TOKEN>
              token: <JWT_TOKEN>
              type: bearer
        "400":
          description: bad request (missing one of params)
          examples:
            application/json:
              message: empty required payload attributes
        "401":
          description: invalid credentials
          examples:
            application/json:
              message: invalid credentials for user 'vsantos'
      tags:
      - JWT
  /api/v1/users:
    post:
      consumes:
      - application/json
      description: Creates an user
      operationId: create
      parameters:
      - description: application/json
        in: headers
        name: content-type
        required: true
      - description: user payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/User'
      produces:
      - application/json
      responses:
        "201":
          description: returned user
          examples:
            application/json:
              id: <USER_ID>
              message: created user '<USER_LOGIN>'
        "500":
          description: internal server error
          examples:
            application/json:
              details: <ERROR_DETAILS>
              message: could not create user
      tags:
      - Users
  /health:
    get:
      consumes:
      - application/json
      description: Returns the API can be considered operational
      operationId: get
      produces:
      - application/json
      responses:
        "200":
          description: healthy components
          examples:
            application/json:
              database: healthy
        "500":
          description: unhealthy components
          examples:
            application/json:
              database: unhealthy
      tags:
      - Healthchecks
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
