version: '3.7'

services:
  mongodb:
    image: mongo:4.4.0
    container_name: mongodb
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: "budget-user"
    #   MONGO_INITDB_ROOT_PASSWORD: "budget-password"
    #   MONGO_INITDB_DATABASE: "budget-tracker"
    ports:
        - 27017:27017
  mongo_seed:
    build: ./mongo-seed
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh
